language: node_js
node_js:
  - "4"
  - "6"
env:
  - TEST_DIR=tools
before_script:
  - cd $TEST_DIR
script:
  - npm run jsHint -- --failTaskOnError
  - npm run test -- --failTaskOnError --suppressPassed
